# Generated by Django 4.2 on 2025-08-31 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='reference_link',
            field=models.URLField(blank=True, help_text='Optional: Add a GFG or YouTube link for explanation.', null=True),
        ),
    ]
