# Generated by Django 4.2 on 2025-09-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_question_reference_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='responses',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
