# Generated by Django 4.2 on 2025-08-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_quiz_question_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='reference_link',
            field=models.URLField(blank=True, help_text='Optional: Add a GFG or YouTube link for this tutorial.', null=True),
        ),
    ]
